### PR TITLE
MILESTONE 3:  CONTACT FORM

### PR DESCRIPTION
**Pull request by JuniorGarciaRodriguez**
### Completed:
- [X] Test different browsers (error from the previous attempt)
- [X] Setup folders tree
- [X] Setup linters
- [X] Setup GitHub actions to run tests on pull request
- [X] Header section
- [X] Headline section
- [X] HTML setup
- [X] Adjust relative units to match the Figma template
- [X] Projects section
- [X] About Me section
- [X] Contact Me form

### Pending:
- [ ] Animations
- [ ] RWD-CSS
- [ ] Media queries for the desktop version

### CODE REVIEW

**Review by LionRouge1 — COMMENTED** [review]
Hi @team, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, with a branch that doesn't have the name of a feature or action (e.g. 'created_contact_form', 'contact_form'). Kindly [rename the branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) or create a new branch with a feature or action name

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by JuniorGarciaRodriguez** [comment]
@LionRouge1 Please verify that this is the development branch. The feature branch is based on this one for ease of deployment

**Comment by LionRouge1** [comment]
@JuniorGarciaRodriguez  Please you have to implement the contact form in a feature branch and create the PR from the new feature branch to your default branch(main or master). In case you want to use a development branch (It is not requested for this milestone), the branch development branch has to be the default branch where you will merge the features branches.

But in your case and regarding this project you have to create a feature branch and create a PR to the default branch (main or master). You can use the branch "Active-Development" for deployment when your project is completely done and approved

I hope it is clear to you @JuniorGarciaRodriguez ?

**Comment by JuniorGarciaRodriguez** [comment]
It's not clear at all honestly. If I deploy the branch after approval there is no point as the reviewer won't see the most recent commits as far as I understand until the feature is merged. I've always worked with this workflow. You are the first one to make that requirement which is not specified in the activities nor the provided GitHub workflow from the lessons. Kindly point me to the corresponding source or guideline to read it in my free time. Thank you @LionRouge1

**Comment by LionRouge1** [comment]
@JuniorGarciaRodriguez, Sorry maybe I'm not getting your point because when you deploy a project, it's to make it open to the public. And I think that you should request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). Sorry for any inconvenient :disappointed:

**Review by MaganaAsiati — APPROVED** [review]
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @JuniorGarciaRodriguez , I'm @MaganaAsiati , your reviewer for this PR  :wave: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


clap

## Highlights
- descriptive README file  :heavy_check_mark:👨🏻‍💻
- Your commits should start with a capital letter :heavy_check_mark:👨🏻‍💻


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [ ] kindly  Add a descriptive description in your pull request in future which give more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Cheers and Happy coding!👏👏👏

**Pull request merged**
